/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ChoreNotifier | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateNotificationMethodRequest,
  ProblemDetails
} from '../choreNotifierV1.schemas';





export const addNotificationPreference = (
    userId: number,
    createNotificationMethodRequest: CreateNotificationMethodRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/users/${userId}/notification-preferences`,
      createNotificationMethodRequest,options
    );
  }



export const getAddNotificationPreferenceMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNotificationPreference>>, TError,{userId: number;data: CreateNotificationMethodRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addNotificationPreference>>, TError,{userId: number;data: CreateNotificationMethodRequest}, TContext> => {

const mutationKey = ['addNotificationPreference'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addNotificationPreference>>, {userId: number;data: CreateNotificationMethodRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  addNotificationPreference(userId,data,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type AddNotificationPreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof addNotificationPreference>>>
    export type AddNotificationPreferenceMutationBody = CreateNotificationMethodRequest
    export type AddNotificationPreferenceMutationError = AxiosError<ProblemDetails>

    export const useAddNotificationPreference = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNotificationPreference>>, TError,{userId: number;data: CreateNotificationMethodRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addNotificationPreference>>,
        TError,
        {userId: number;data: CreateNotificationMethodRequest},
        TContext
      > => {

      const mutationOptions = getAddNotificationPreferenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
