/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ChoreNotifier | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CompleteChoreDto,
  SnoozeChoreDto
} from '../choreNotifierV1.schemas';





export const snoozeChore = (
    choreOccurrenceId: number,
    snoozeChoreDto: SnoozeChoreDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/chore-occurrences/${choreOccurrenceId}/snooze`,
      snoozeChoreDto,options
    );
  }



export const getSnoozeChoreMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof snoozeChore>>, TError,{choreOccurrenceId: number;data: SnoozeChoreDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof snoozeChore>>, TError,{choreOccurrenceId: number;data: SnoozeChoreDto}, TContext> => {

const mutationKey = ['snoozeChore'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof snoozeChore>>, {choreOccurrenceId: number;data: SnoozeChoreDto}> = (props) => {
          const {choreOccurrenceId,data} = props ?? {};

          return  snoozeChore(choreOccurrenceId,data,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type SnoozeChoreMutationResult = NonNullable<Awaited<ReturnType<typeof snoozeChore>>>
    export type SnoozeChoreMutationBody = SnoozeChoreDto
    export type SnoozeChoreMutationError = AxiosError<unknown>

    export const useSnoozeChore = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof snoozeChore>>, TError,{choreOccurrenceId: number;data: SnoozeChoreDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof snoozeChore>>,
        TError,
        {choreOccurrenceId: number;data: SnoozeChoreDto},
        TContext
      > => {

      const mutationOptions = getSnoozeChoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const completeChore = (
    choreOccurrenceId: number,
    completeChoreDto: CompleteChoreDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/chore-occurrences/${choreOccurrenceId}/complete`,
      completeChoreDto,options
    );
  }



export const getCompleteChoreMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeChore>>, TError,{choreOccurrenceId: number;data: CompleteChoreDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof completeChore>>, TError,{choreOccurrenceId: number;data: CompleteChoreDto}, TContext> => {

const mutationKey = ['completeChore'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeChore>>, {choreOccurrenceId: number;data: CompleteChoreDto}> = (props) => {
          const {choreOccurrenceId,data} = props ?? {};

          return  completeChore(choreOccurrenceId,data,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type CompleteChoreMutationResult = NonNullable<Awaited<ReturnType<typeof completeChore>>>
    export type CompleteChoreMutationBody = CompleteChoreDto
    export type CompleteChoreMutationError = AxiosError<unknown>

    export const useCompleteChore = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeChore>>, TError,{choreOccurrenceId: number;data: CompleteChoreDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeChore>>,
        TError,
        {choreOccurrenceId: number;data: CompleteChoreDto},
        TContext
      > => {

      const mutationOptions = getCompleteChoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
