/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ChoreNotifier | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateChoreRequest,
  ListChoresParams,
  Result,
  UpdateChoreDto
} from '../choreNotifierV1.schemas';





export const updateChore = (
    choreId: number,
    updateChoreDto: UpdateChoreDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Result>> => {


    return axios.default.put(
      `/api/chores/${choreId}`,
      updateChoreDto,options
    );
  }



export const getUpdateChoreMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChore>>, TError,{choreId: number;data: UpdateChoreDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateChore>>, TError,{choreId: number;data: UpdateChoreDto}, TContext> => {

const mutationKey = ['updateChore'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateChore>>, {choreId: number;data: UpdateChoreDto}> = (props) => {
          const {choreId,data} = props ?? {};

          return  updateChore(choreId,data,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type UpdateChoreMutationResult = NonNullable<Awaited<ReturnType<typeof updateChore>>>
    export type UpdateChoreMutationBody = UpdateChoreDto
    export type UpdateChoreMutationError = AxiosError<unknown>

    export const useUpdateChore = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChore>>, TError,{choreId: number;data: UpdateChoreDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateChore>>,
        TError,
        {choreId: number;data: UpdateChoreDto},
        TContext
      > => {

      const mutationOptions = getUpdateChoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const removeChoreAssignee = (
    choreId: number,
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/chores/${choreId}/assignees/${userId}`,options
    );
  }



export const getRemoveChoreAssigneeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeChoreAssignee>>, TError,{choreId: number;userId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeChoreAssignee>>, TError,{choreId: number;userId: number}, TContext> => {

const mutationKey = ['removeChoreAssignee'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeChoreAssignee>>, {choreId: number;userId: number}> = (props) => {
          const {choreId,userId} = props ?? {};

          return  removeChoreAssignee(choreId,userId,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type RemoveChoreAssigneeMutationResult = NonNullable<Awaited<ReturnType<typeof removeChoreAssignee>>>

    export type RemoveChoreAssigneeMutationError = AxiosError<unknown>

    export const useRemoveChoreAssignee = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeChoreAssignee>>, TError,{choreId: number;userId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeChoreAssignee>>,
        TError,
        {choreId: number;userId: number},
        TContext
      > => {

      const mutationOptions = getRemoveChoreAssigneeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const addChoreAssignee = (
    choreId: number,
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Result>> => {


    return axios.default.post(
      `/api/chores/${choreId}/assignees/${userId}`,undefined,options
    );
  }



export const getAddChoreAssigneeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChoreAssignee>>, TError,{choreId: number;userId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addChoreAssignee>>, TError,{choreId: number;userId: number}, TContext> => {

const mutationKey = ['addChoreAssignee'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addChoreAssignee>>, {choreId: number;userId: number}> = (props) => {
          const {choreId,userId} = props ?? {};

          return  addChoreAssignee(choreId,userId,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type AddChoreAssigneeMutationResult = NonNullable<Awaited<ReturnType<typeof addChoreAssignee>>>

    export type AddChoreAssigneeMutationError = AxiosError<unknown>

    export const useAddChoreAssignee = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addChoreAssignee>>, TError,{choreId: number;userId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addChoreAssignee>>,
        TError,
        {choreId: number;userId: number},
        TContext
      > => {

      const mutationOptions = getAddChoreAssigneeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listChores = (
    params?: ListChoresParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Result>> => {


    return axios.default.get(
      `/api/chores`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListChoresInfiniteQueryKey = (params?: ListChoresParams,) => {
    return [
    'infinite', `/api/chores`, ...(params ? [params]: [])
    ] as const;
    }

export const getListChoresQueryKey = (params?: ListChoresParams,) => {
    return [
    `/api/chores`, ...(params ? [params]: [])
    ] as const;
    }


export const getListChoresInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listChores>>, ListChoresParams['afterId']>, TError = AxiosError<unknown>>(params?: ListChoresParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChoresInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChores>>, QueryKey, ListChoresParams['afterId']> = ({ signal, pageParam }) => listChores({...params, 'afterId': pageParam || params?.['afterId']}, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChoresInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listChores>>>
export type ListChoresInfiniteQueryError = AxiosError<unknown>


export function useListChoresInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChores>>, ListChoresParams['afterId']>, TError = AxiosError<unknown>>(
 params: undefined |  ListChoresParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChores>>,
          TError,
          Awaited<ReturnType<typeof listChores>>, QueryKey
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChoresInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChores>>, ListChoresParams['afterId']>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChores>>,
          TError,
          Awaited<ReturnType<typeof listChores>>, QueryKey
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChoresInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChores>>, ListChoresParams['afterId']>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListChoresInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChores>>, ListChoresParams['afterId']>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData, QueryKey, ListChoresParams['afterId']>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChoresInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListChoresQueryOptions = <TData = Awaited<ReturnType<typeof listChores>>, TError = AxiosError<unknown>>(params?: ListChoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChoresQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChores>>> = ({ signal }) => listChores(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChoresQueryResult = NonNullable<Awaited<ReturnType<typeof listChores>>>
export type ListChoresQueryError = AxiosError<unknown>


export function useListChores<TData = Awaited<ReturnType<typeof listChores>>, TError = AxiosError<unknown>>(
 params: undefined |  ListChoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChores>>,
          TError,
          Awaited<ReturnType<typeof listChores>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChores<TData = Awaited<ReturnType<typeof listChores>>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChores>>,
          TError,
          Awaited<ReturnType<typeof listChores>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChores<TData = Awaited<ReturnType<typeof listChores>>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListChores<TData = Awaited<ReturnType<typeof listChores>>, TError = AxiosError<unknown>>(
 params?: ListChoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChores>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createChore = (
    createChoreRequest: CreateChoreRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/chores`,
      createChoreRequest,options
    );
  }



export const getCreateChoreMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChore>>, TError,{data: CreateChoreRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createChore>>, TError,{data: CreateChoreRequest}, TContext> => {

const mutationKey = ['createChore'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChore>>, {data: CreateChoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  createChore(data,axiosOptions)
        }




  return  { mutationFn, ...mutationOptions }}

    export type CreateChoreMutationResult = NonNullable<Awaited<ReturnType<typeof createChore>>>
    export type CreateChoreMutationBody = CreateChoreRequest
    export type CreateChoreMutationError = AxiosError<unknown>

    export const useCreateChore = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChore>>, TError,{data: CreateChoreRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createChore>>,
        TError,
        {data: CreateChoreRequest},
        TContext
      > => {

      const mutationOptions = getCreateChoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
