/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ChoreNotifier | v1
 * OpenAPI spec version: 1.0.0
 */
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CompleteChoreDtoUserId = number | string;

export interface CompleteChoreDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: CompleteChoreDtoUserId;
}

export type CreateChoreRequestDescription = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateChoreRequestAssigneeUserIdsItem = number | string;

export interface CreateChoreRequest {
  title: string;
  description: CreateChoreRequestDescription;
  choreSchedule: CreateChoreScheduleRequest;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: string;
  assigneeUserIds: CreateChoreRequestAssigneeUserIdsItem[];
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateChoreScheduleRequestIntervalDays = number | string;

export type CreateChoreScheduleRequestUntil = null | string;

export interface CreateChoreScheduleRequest {
  start: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  intervalDays: CreateChoreScheduleRequestIntervalDays;
  until: CreateChoreScheduleRequestUntil;
}

export interface CreateUserRequest {
  name: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type SnoozeChoreDtoUserId = number | string;

export interface SnoozeChoreDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  userId: SnoozeChoreDtoUserId;
}

export type UpdateChoreDtoDescription = null | string;

export type UpdateChoreDtoChoreSchedule = null | CreateChoreScheduleRequest;

export interface UpdateChoreDto {
  title: string;
  description: UpdateChoreDtoDescription;
  choreSchedule: UpdateChoreDtoChoreSchedule;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: string;
}

export interface UpdateUserDto {
  name: string;
}

export type ListUsersParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
afterId?: number | string;
};

export type ListChoresParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
afterId?: number | string;
};
