/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ChoreNotifier | v1
 * OpenAPI spec version: 1.0.0
 */
export type AddChoreAssigneeResponseDescription = null | string;

export interface AddChoreAssigneeResponse {
  id: number;
  title: string;
  description: AddChoreAssigneeResponseDescription;
  choreSchedule: ChoreScheduleResponse;
  assignees: ChoreAssigneeResponse[];
}

export interface ChoreAssigneeResponse {
  id: number;
  name: string;
}

export type ChoreOccurenceFilter = typeof ChoreOccurenceFilter[keyof typeof ChoreOccurenceFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChoreOccurenceFilter = {
  All: 'All',
  Completed: 'Completed',
  Upcoming: 'Upcoming',
  Due: 'Due',
} as const;

export type ChoreScheduleResponseUntil = null | string;

export interface ChoreScheduleResponse {
  start: string;
  intervalDays: number;
  until: ChoreScheduleResponseUntil;
}

export interface CompleteChoreDto {
  userId: number;
}

export type CreateChoreRequestDescription = null | string;

export interface CreateChoreRequest {
  title: string;
  description: CreateChoreRequestDescription;
  choreSchedule: CreateChoreScheduleRequest;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: string;
  assigneeUserIds: number[];
}

export type CreateChoreResponseDescription = null | string;

/**
 * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
 */
export type CreateChoreResponseSnoozeDuration = null | string;

export interface CreateChoreResponse {
  id: number;
  title: string;
  description: CreateChoreResponseDescription;
  choreSchedule: ChoreScheduleResponse;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: CreateChoreResponseSnoozeDuration;
  assignees: ChoreAssigneeResponse[];
}

export type CreateChoreScheduleRequestUntil = null | string;

export interface CreateChoreScheduleRequest {
  start: string;
  intervalDays: number;
  until: CreateChoreScheduleRequestUntil;
}

export type CreateNotificationMethodRequest = CreateNotificationMethodRequestCreateConsoleMethodRequest | CreateNotificationMethodRequestCreateNtfyMethodRequest;

export type CreateNotificationMethodRequestCreateConsoleMethodRequestType = typeof CreateNotificationMethodRequestCreateConsoleMethodRequestType[keyof typeof CreateNotificationMethodRequestCreateConsoleMethodRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateNotificationMethodRequestCreateConsoleMethodRequestType = {
  Console: 'Console',
} as const;

export interface CreateNotificationMethodRequestCreateConsoleMethodRequest {
  type: CreateNotificationMethodRequestCreateConsoleMethodRequestType;
  name: string;
}

export type CreateNotificationMethodRequestCreateNtfyMethodRequestType = typeof CreateNotificationMethodRequestCreateNtfyMethodRequestType[keyof typeof CreateNotificationMethodRequestCreateNtfyMethodRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateNotificationMethodRequestCreateNtfyMethodRequestType = {
  Ntfy: 'Ntfy',
} as const;

export interface CreateNotificationMethodRequestCreateNtfyMethodRequest {
  type: CreateNotificationMethodRequestCreateNtfyMethodRequestType;
  topicName: string;
}

export interface CreateUserRequest {
  name: string;
}

export interface CreateUserResponse {
  id: number;
  name: string;
}

export interface GetUserResponse {
  id: number;
  name: string;
}

export type KeysetPageOfListChoresResponseItemAndintNextCursor = null | number;

export interface KeysetPageOfListChoresResponseItemAndint {
  items: ListChoresResponseItem[];
  hasNextPage: boolean;
  nextCursor: KeysetPageOfListChoresResponseItemAndintNextCursor;
  pageSize: number;
}

export type KeysetPageOfListUserChoreOccurrencesResponseItemAndintNextCursor = null | number;

export interface KeysetPageOfListUserChoreOccurrencesResponseItemAndint {
  items: ListUserChoreOccurrencesResponseItem[];
  hasNextPage: boolean;
  nextCursor: KeysetPageOfListUserChoreOccurrencesResponseItemAndintNextCursor;
  pageSize: number;
}

export type KeysetPageOfListUserResponseItemAndintNextCursor = null | number;

export interface KeysetPageOfListUserResponseItemAndint {
  items: ListUserResponseItem[];
  hasNextPage: boolean;
  nextCursor: KeysetPageOfListUserResponseItemAndintNextCursor;
  pageSize: number;
}

export type ListChoresResponseItemDescription = null | string;

export type ListChoresResponseItemChoreSchedule = null | ChoreScheduleResponse;

/**
 * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
 */
export type ListChoresResponseItemSnoozeDuration = null | string;

export interface ListChoresResponseItem {
  id: number;
  title: string;
  description: ListChoresResponseItemDescription;
  choreSchedule: ListChoresResponseItemChoreSchedule;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: ListChoresResponseItemSnoozeDuration;
}

export type ListUserChoreOccurrencesChoreResponseItemDescription = null | string;

/**
 * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
 */
export type ListUserChoreOccurrencesChoreResponseItemSnoozeDuration = null | string;

export interface ListUserChoreOccurrencesChoreResponseItem {
  id: number;
  title: string;
  description: ListUserChoreOccurrencesChoreResponseItemDescription;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: ListUserChoreOccurrencesChoreResponseItemSnoozeDuration;
}

export type ListUserChoreOccurrencesResponseItemCompletedAt = null | string;

export interface ListUserChoreOccurrencesResponseItem {
  id: number;
  originalDueAt: string;
  currentDueAt: string;
  completedAt: ListUserChoreOccurrencesResponseItemCompletedAt;
  isCompleted: boolean;
  isDue: boolean;
  chore: ListUserChoreOccurrencesChoreResponseItem;
}

export interface ListUserResponseItem {
  id: number;
  name: string;
}

export type ProblemDetailsType = null | string;

export type ProblemDetailsTitle = null | string;

export type ProblemDetailsStatus = null | number;

export type ProblemDetailsDetail = null | string;

export type ProblemDetailsInstance = null | string;

export interface ProblemDetails {
  type?: ProblemDetailsType;
  title?: ProblemDetailsTitle;
  status?: ProblemDetailsStatus;
  detail?: ProblemDetailsDetail;
  instance?: ProblemDetailsInstance;
}

export interface SnoozeChoreDto {
  userId: number;
}

export type UpdateChoreDtoDescription = null | string;

export type UpdateChoreDtoChoreSchedule = null | CreateChoreScheduleRequest;

export interface UpdateChoreDto {
  title: string;
  description: UpdateChoreDtoDescription;
  choreSchedule: UpdateChoreDtoChoreSchedule;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: string;
}

export type UpdateChoreResponseDescription = null | string;

/**
 * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
 */
export type UpdateChoreResponseSnoozeDuration = null | string;

export interface UpdateChoreResponse {
  id: number;
  title: string;
  description: UpdateChoreResponseDescription;
  choreSchedule: ChoreScheduleResponse;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  snoozeDuration: UpdateChoreResponseSnoozeDuration;
}

export interface UpdateUserDto {
  name: string;
}

export interface UpdateUserResponse {
  id: number;
  name: string;
}

export type ListUsersParams = {
pageSize?: number;
afterId?: number;
};

export type ListUserChoreOccurrencesParams = {
pageSize?: number;
afterId?: number;
filter?: ChoreOccurenceFilter;
};

export type ListChoresParams = {
pageSize?: number;
afterId?: number;
};
