// <auto-generated />
using System;
using ChoreNotifier.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChoreNotifier.Migrations
{
    [DbContext(typeof(ChoreDbContext))]
    [Migration("20260116234900_CascadeUserDeletion")]
    partial class CascadeUserDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChoreNotifier.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NextAssigneeIndex")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("SnoozeDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("ChoreNotifier.Models.ChoreAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreAssignees");
                });

            modelBuilder.Entity("ChoreNotifier.Models.ChoreOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreOccurrences");
                });

            modelBuilder.Entity("ChoreNotifier.Models.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("NotificationAttempts");
                });

            modelBuilder.Entity("ChoreNotifier.Models.NotificationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationMethods");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChoreNotifier.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChoreNotifier.Models.ConsoleMethod", b =>
                {
                    b.HasBaseType("ChoreNotifier.Models.NotificationMethod");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ChoreNotifier.Models.NtfyMethod", b =>
                {
                    b.HasBaseType("ChoreNotifier.Models.NotificationMethod");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ChoreNotifier.Models.Chore", b =>
                {
                    b.OwnsOne("ChoreNotifier.Models.ChoreSchedule", "ChoreSchedule", b1 =>
                        {
                            b1.Property<int>("ChoreId")
                                .HasColumnType("integer");

                            b1.Property<int>("IntervalDays")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("Until")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ChoreId");

                            b1.ToTable("Chores");

                            b1.WithOwner()
                                .HasForeignKey("ChoreId");
                        });

                    b.Navigation("ChoreSchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("ChoreNotifier.Models.ChoreAssignee", b =>
                {
                    b.HasOne("ChoreNotifier.Models.Chore", "Chore")
                        .WithMany("Assignees")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoreNotifier.Models.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChoreNotifier.Models.ChoreOccurrence", b =>
                {
                    b.HasOne("ChoreNotifier.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoreNotifier.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChoreNotifier.Models.NotificationAttempt", b =>
                {
                    b.HasOne("ChoreNotifier.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChoreNotifier.Models.Notification", "Notification", b1 =>
                        {
                            b1.Property<Guid>("NotificationAttemptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NotificationAttemptId");

                            b1.ToTable("NotificationAttempts");

                            b1.WithOwner()
                                .HasForeignKey("NotificationAttemptId");
                        });

                    b.Navigation("Notification")
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ChoreNotifier.Models.NotificationMethod", b =>
                {
                    b.HasOne("ChoreNotifier.Models.User", null)
                        .WithOne("NotificationPreference")
                        .HasForeignKey("ChoreNotifier.Models.NotificationMethod", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChoreNotifier.Models.Chore", b =>
                {
                    b.Navigation("Assignees");
                });

            modelBuilder.Entity("ChoreNotifier.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("NotificationPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
